[package]
name = "javaclass-rs"
version = "0.1.0"
authors = ["Ian Rehwinkel <ian.rehwinkel@tutanota.com>"]
edition = "2018"

[lib]
name = "javaclass"
path = "src/lib.rs"

[dependencies]
serde = { version = "1.0.105", features = ["derive"] }
